FAIL_REASON_ORDER = [
    "FAIL_NO_RGB_STREAM",
    "FAIL_ANALYSIS_ERROR",
    "FAIL_SYNC_P95_GT_FAIL",
    "FAIL_DROP_RATIO_GT_FAIL",
    "FAIL_NO_CLEAN_SEGMENTS_LONG_ENOUGH",
]

WARN_REASON_ORDER = [
    "WARN_DEPTH_TIMESTAMP_MISSING",
    "WARN_DEPTH_PIXEL_DECODE_UNSUPPORTED",
    "WARN_RGB_PIXEL_DECODE_UNSUPPORTED",
    "WARN_SYNC_P95_GT_WARN",
    "WARN_DROP_RATIO_GT_WARN",
    "WARN_IMU_MISSING_RATIO_GT_WARN",
    "WARN_BLUR_FAIL_RATIO_GT_WARN",
    "WARN_EXPOSURE_BAD_RATIO_GT_WARN",
    "WARN_DEPTH_INVALID_MEAN_GT_WARN",
]

RECOMMENDED_ACTION = {
    "PASS": "USE_FULL_SEQUENCE",
    "WARN": "USE_SEGMENTS_ONLY",
    "FAIL": "RECAPTURE_OR_SKIP",
}
